import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Shared/Navbar";

const poppins = Poppins({
  weight: ["300", "400", "500", "700", "800"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className}  antialiased`}>
        <header>
          <Navbar></Navbar>
        </header>
        <main>{children}</main>
        <footer></footer>
      </body>
    </html>
  );
}
